---
galaxy_info:
  author: dang
  description: Samba file server configuration
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []
