[global]
	workgroup = GOEPP
	server string = %h server (Samba, Ubuntu)
	log file = /var/log/samba/log.%m
	max log size = 1000
	logging = file
	panic action = /usr/share/samba/panic-action %d
	server role = standalone server
	obey pam restrictions = yes
	unix password sync = yes
	passwd program = /usr/bin/passwd %u
	passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
	pam password change = yes
	map to guest = bad user
	usershare allow guests = yes
	guest ok = no
	read only = no
	browseable = yes
	map archive = no
	map hidden = no
	map acl inherit = yes
	nt acl support = no
	vfs objects = catia fruit streams_xattr acl_xattr
	fruit:encoding = native
	fruit:metadata = stream
	fruit:zero_file_id = yes
	fruit:nfs_aces = no

[media]
	path = /mnt/media
	valid users = dang,linux

[kopia-hdd]
	path = /mnt/kopia-hdd
	valid users = dang,linux

[fcp]
	path = /mnt/fcp
	valid users = dang,linux

[dang-home]
	path = /mnt/homes/dang
	valid users = dang

[jen-home]
	path = /mnt/homes/jen
	valid users = jen

[backups]
	path = /mnt/backups
	valid users = dang

[k3s-prod-data]
	path = /mnt/k3s-prod-data
	valid users = dang
	create mask = 0644
	force create mode = 0644
	directory mask = 0755
	force directory mode = 0755
	force user = root
	force group = root

[k3s-lab-data]
	path = /mnt/k3s-lab-data
	valid users = dang
	create mask = 0644
	force create mode = 0644
	directory mask = 0755
	force directory mode = 0755
	force user = root
	force group = root
