---
# Configure and manage gru server
#
# Usage:
#   ansible-playbook playbooks/ssh/host-gru.yaml
#   ansible-playbook playbooks/ssh/host-gru.yaml -e apt_dist_upgrade=true

- name: Configure gru server
  hosts: "gru"
  become: true
  gather_facts: true

  tasks:
    - name: Run common role
      ansible.builtin.include_role:
        name: common
