---
- name: Run system updates and upgrades
  hosts: "{{ target_host | default('localhost') }}"
  become: true

  pre_tasks:
    - name: Fail if no target_host is specified
      ansible.builtin.fail:
        msg: "You must specify a target_host variable. Use -e target_host=hostname"
      when: target_host is not defined
      delegate_to: localhost

  tasks:
    - name: Run system updates and upgrades
      ansible.builtin.include_role:
        name: common
        tasks_from: update-upgrade
