---
# K3s Application Definitions
# This file defines all K3s applications and their deployment configurations
# Used by playbooks/k3s/update-app.yaml to dynamically route updates
#
# Note: Paths use playbook_dir which resolves relative to the calling playbook
# The unified playbook is at playbooks/k3s/update-app.yaml, so paths are relative to that location

# Common configuration variables
# Note: k3s_config_base_path and scripts_base_path are set in the playbook
# using playbook_dir to ensure correct path resolution
k3s_default_context: "k3s-prod"

k3s_applications:
  alertmanager:
    deployment_method: helm
    helm_release_name: alertmanager
    helm_chart_name: prometheus-community/alertmanager
    helm_repo_name: prometheus-community
    helm_repo_url: https://prometheus-community.github.io/helm-charts
    helm_namespace: alertmanager
    helm_values_file: "{{ playbook_dir }}/../../files/k3s-config/alertmanager/helm/alertmanager-values-prod.yaml"
    k8s_context: k3s-prod

  cert-manager:
    deployment_method: helm
    helm_release_name: cert-manager
    helm_chart_name: jetstack/cert-manager
    helm_repo_name: jetstack
    helm_repo_url: https://charts.jetstack.io
    helm_namespace: cert-manager
    helm_values_file: "{{ playbook_dir }}/../../files/k3s-config/cert-manager/helm/cert-manager-values-prod.yaml"
    k8s_context: k3s-prod

  cnpg-operator:
    deployment_method: helm
    helm_release_name: cloudnative-pg
    helm_chart_name: cnpg/cloudnative-pg
    helm_repo_name: cnpg
    helm_repo_url: https://cloudnative-pg.github.io/charts
    helm_namespace: cnpg-system
    helm_values_file: "{{ playbook_dir }}/../../files/k3s-config/cnpg/helm/cnpg-operator-values-prod.yaml"
    k8s_context: k3s-prod

  cnpg:
    deployment_method: manifest-multi-cnpg
    instances:
      - name: grafana
        context: k3s-prod
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/cnpg/manifests/cnpg-prod-grafana.yml"
        cluster_name: grafana-prod
        service_namespace: cnpg-grafana
      - name: homeassistant
        context: k3s-prod
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/cnpg/manifests/cnpg-prod-homeassistant.yml"
        cluster_name: homeassistant-prod
        service_namespace: cnpg-homeassistant
      - name: hertzbeat
        context: k3s-prod
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/cnpg/manifests/cnpg-prod-hertzbeat.yml"
        cluster_name: hertzbeat-prod
        service_namespace: cnpg-hertzbeat

  esphome:
    deployment_method: manifest
    manifest_path: "{{ playbook_dir }}/../../files/k3s-config/esphome/manifests/esphome-prod.yaml"

  fluent-bit:
    deployment_method: helm
    helm_release_name: fluent-bit
    helm_chart_name: fluent/fluent-bit
    helm_repo_name: fluent
    helm_repo_url: https://fluent.github.io/helm-charts
    helm_namespace: fluent-bit
    helm_values_file: "{{ playbook_dir }}/../../files/k3s-config/fluent-bit/helm/fluent-bit-values-prod.yaml"
    k8s_context: k3s-prod

  grafana:
    deployment_method: manifest
    manifest_path: "{{ playbook_dir }}/../../files/k3s-config/grafana/manifests/grafana-deployment.yaml"

  hertzbeat:
    deployment_method: manifest
    manifest_path: "{{ playbook_dir }}/../../files/k3s-config/hertzbeat/manifests/hertzbeat-prod.yml"
    k8s_context: k3s-prod
    service_namespace: hertzbeat
    deployment_name: hertzbeat
    app_label: hertzbeat

  homeassistant:
    deployment_method: manifest-multi
    instances:
      - name: morgspi
        context: k3s-morgspi
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/homeassistant/manifests/homeassistant-morgspi.yaml"
        deployment_name: homeassistant
        service_namespace: homeassistant
        app_label: homeassistant
      - name: mudderpi
        context: k3s-mudderpi
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/homeassistant/manifests/homeassistant-mudderpi.yaml"
        deployment_name: homeassistant
        service_namespace: homeassistant
        app_label: homeassistant
      - name: prod
        context: k3s-prod
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/homeassistant/manifests/homeassistant-prod.yaml"
        deployment_name: homeassistant
        service_namespace: homeassistant
        app_label: homeassistant

  metallb:
    deployment_method: helm
    helm_release_name: metallb
    helm_chart_name: metallb/metallb
    helm_repo_name: metallb
    helm_repo_url: https://metallb.github.io/metallb
    helm_namespace: metallb-system
    helm_values_file: "{{ playbook_dir }}/../../files/k3s-config/metallb/helm/metallb-values-prod.yaml"
    k8s_context: k3s-prod

  mongodb-operator:
    deployment_method: helm
    helm_release_name: community-operator
    helm_chart_name: mongodb/community-operator
    helm_repo_name: mongodb
    helm_repo_url: https://mongodb.github.io/helm-charts
    helm_namespace: mongodb
    helm_values_file: "{{ playbook_dir }}/../../files/k3s-config/mongodb/helm/mongodb-operator-values-prod.yaml"
    k8s_context: k3s-prod

  n8n:
    deployment_method: manifest

  opensearch:
    deployment_method: helm
    helm_release_name: opensearch
    helm_chart_name: opensearch/opensearch
    helm_repo_name: opensearch
    helm_repo_url: https://opensearch-project.github.io/helm-charts/
    helm_namespace: opensearch
    helm_values_file: "{{ playbook_dir }}/../../files/k3s-config/opensearch/helm/opensearch-values-prod.yaml"
    k8s_context: k3s-prod

  pgadmin:
    deployment_method: helm
    helm_release_name: pgadmin4
    helm_chart_name: runix/pgadmin4
    helm_repo_name: runix
    helm_repo_url: https://helm.runix.net
    helm_namespace: pgadmin
    helm_values_file: "{{ playbook_dir }}/../../files/k3s-config/pgadmin/helm/pgadmin-values-prod.yaml"
    k8s_context: k3s-prod

  postfix:
    deployment_method: manifest

  telegraf:
    deployment_method: manifest-multi
    instances:
      - name: vm
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/telegraf/manifests/telegraf-prod-vm.yaml"
        deployment_name: telegraf-vm
        app_label: telegraf
      - name: graylog
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/telegraf/manifests/telegraf-prod-graylog.yaml"
        deployment_name: telegraf-graylog
        app_label: telegraf

  traefik:
    deployment_method: helm
    helm_release_name: traefik
    helm_chart_name: traefik/traefik
    helm_repo_name: traefik
    helm_repo_url: https://traefik.github.io/charts
    helm_namespace: traefik
    helm_values_file: "{{ playbook_dir }}/../../files/k3s-config/traefik/helm/traefik-values-prod.yaml"
    k8s_context: k3s-prod

  victoriametrics:
    deployment_method: manifest-multi
    instances:
      - name: vmsingle
        context: "{{ k3s_default_context }}"
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/victoriametrics/manifests/victoriametrics-prod-vmsingle.yaml"
        deployment_name: vmsingle-vms-prod
        service_namespace: victoriametrics
        app_label: vmsingle
      - name: vmsingle-lt
        context: "{{ k3s_default_context }}"
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/victoriametrics/manifests/victoriametrics-prod-vmsingle-lt.yaml"
        deployment_name: vmsingle-vms-prod-lt
        service_namespace: victoriametrics
        app_label: vmsingle
      - name: vmagent
        context: "{{ k3s_default_context }}"
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/victoriametrics/manifests/victoriametrics-prod-vmagent.yaml"
        deployment_name: vmagent-vma-prod
        service_namespace: victoriametrics
        app_label: vmagent

  victoriametrics-operator:
    deployment_method: helm
    helm_release_name: victoria-metrics-operator
    helm_chart_name: vm/victoria-metrics-operator
    helm_repo_name: vm
    helm_repo_url: https://victoriametrics.github.io/helm-charts/
    helm_namespace: victoriametrics
    helm_values_file: "{{ playbook_dir }}/../../files/k3s-config/victoriametrics/helm/victoriametrics-operator-values-prod.yaml"
    k8s_context: k3s-prod

  weather:
    deployment_method: helm
    helm_release_name: weather
    helm_chart_path: "{{ playbook_dir }}/../../files/k3s-config/weather/helm/weather"
    helm_namespace: weather
    helm_values_file: "{{ playbook_dir }}/../../files/k3s-config/weather/helm/weather-values-prod.yaml"
    k8s_context: k3s-prod

  zigbee2mqtt:
    deployment_method: manifest-multi
    instances:
      - name: "11"
        context: k3s-prod
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/zigbee2mqtt/manifests/zigbee2mqtt-prod-11.yaml"
        deployment_name: zigbee11
        service_namespace: zigbee2mqtt
        app_label: zigbee11
      - name: "15"
        context: k3s-prod
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/zigbee2mqtt/manifests/zigbee2mqtt-prod-15.yaml"
        deployment_name: zigbee15
        service_namespace: zigbee2mqtt
        app_label: zigbee15
