---
galaxy_info:
  author: dang
  description: Backup server configuration and scheduling
  company: ""
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - backup
    - cron
    - victoriametrics

dependencies: []
