- name: Install nut package
  ansible.builtin.apt:
    name:
      - nut
    state: present
    update_cache: true

- name: Generate ups.conf from template
  ansible.builtin.template:
    src: "ups.conf.j2"
    dest: /etc/nut/ups.conf
    mode: '0640'
    owner: root
    group: nut
    backup: true
  notify:
    - Restart nut-server
    - Restart nut-monitor

- name: Generate upsd.conf from template
  ansible.builtin.template:
    src: "upsd.conf.j2"
    dest: /etc/nut/upsd.conf
    mode: '0640'
    owner: root
    group: nut
    backup: true
  notify:
    - Restart nut-server
    - Restart nut-monitor

- name: Generate upsd.users from template
  ansible.builtin.template:
    src: "upsd.users.j2"
    dest: /etc/nut/upsd.users
    mode: '0640'
    owner: root
    group: nut
    backup: true
  notify:
    - Restart nut-server
    - Restart nut-monitor

- name: Generate upsmon.conf from template
  ansible.builtin.template:
    src: "upsmon.conf.j2"
    dest: /etc/nut/upsmon.conf
    mode: '0640'
    owner: root
    group: nut
    backup: true
  notify:
    - Restart nut-server
    - Restart nut-monitor

- name: Generate nut.conf from template
  ansible.builtin.template:
    src: "nut.conf.j2"
    dest: /etc/nut/nut.conf
    mode: '0640'
    owner: root
    group: nut
    backup: true
  notify:
    - Restart nut-server
    - Restart nut-monitor
