---
- name: Reboot system
  ansible.builtin.reboot:

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u
  changed_when: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Set password for user ed
  ansible.builtin.user:
    name: ed
    password: "{{ 'changeme' | password_hash('sha512') }}"

- name: Create .ssh directory for user ed
  ansible.builtin.file:
    path: /home/ed/.ssh
    state: directory
    owner: ed
    group: ed
    mode: '0700'
