---
- name: Upgrade Telegraf VM deployment using local manifest
  hosts: localhost
  gather_facts: false
  vars:
    service_name: "telegraf"
    deployment_name: "telegraf-vm"
    app_label: "telegraf"
  tasks:
    - name: Run manifest upgrade tasks for Telegraf VM
      include_tasks: ../tasks/common-update-manifest.yaml
      vars:
        manifest_path: "{{ playbook_dir }}/../../k3s-config/telegraf/manifests/telegraf-prod-vm.yaml"

- name: Upgrade Telegraf Graylog deployment using local manifest
  hosts: localhost
  gather_facts: false
  vars:
    service_name: "telegraf"
    deployment_name: "telegraf-graylog"
    app_label: "telegraf"
  tasks:
    - name: Run manifest upgrade tasks for Telegraf Graylog
      include_tasks: ../tasks/common-update-manifest.yaml
      vars:
        manifest_path: "{{ playbook_dir }}/../../k3s-config/telegraf/manifests/telegraf-prod-graylog.yaml"