---
- name: Upgrade HerzBeat using local manifest
  hosts: localhost
  gather_facts: false
  vars:
    hertzbeat_manifest_path: "{{ playbook_dir }}/../../k3s-config/hertzbeat/manifests/hertzbeat-prod.yml"
    k8s_context: "k3s-prod"
    hertzbeat_namespace: "hertzbeat"
    hertzbeat_deployment_name: "hertzbeat"
  tasks:
    - name: Display upgrade parameters
      debug:
        msg:
          - "HerzBeat Upgrade Parameters:"
          - "  Manifest Path: {{ hertzbeat_manifest_path }}"
          - "  Kubernetes Context: {{ k8s_context }}"
          - "  Namespace: {{ hertzbeat_namespace }}"

    - name: Verify manifest file exists
      stat:
        path: "{{ hertzbeat_manifest_path }}"
      register: manifest_file
      failed_when: not manifest_file.stat.exists

    - name: Get current HerzBeat deployment (before upgrade)
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: "{{ hertzbeat_deployment_name }}"
        namespace: "{{ hertzbeat_namespace }}"
        context: "{{ k8s_context }}"
      register: hertzbeat_current_deployment
      ignore_errors: true

    - name: Display current HerzBeat status
      debug:
        msg:
          - "Current HerzBeat Deployment:"
          - "  Name: {{ hertzbeat_current_deployment.resources[0].metadata.name | default('Not found') }}"
          - "  Image: {{ hertzbeat_current_deployment.resources[0].spec.template.spec.containers[0].image | default('Unknown') }}"
          - "  Ready Replicas: {{ hertzbeat_current_deployment.resources[0].status.readyReplicas | default(0) }}/{{ hertzbeat_current_deployment.resources[0].status.replicas | default(0) }}"
          - "  Status: {{ hertzbeat_current_deployment.resources[0].status.conditions[-1].type | default('Unknown') if hertzbeat_current_deployment.resources[0].status.conditions is defined else 'Unknown' }}"
      when: hertzbeat_current_deployment.resources is defined and hertzbeat_current_deployment.resources | length > 0

    - name: Display status if HerzBeat deployment not found
      debug:
        msg: "HerzBeat deployment '{{ hertzbeat_deployment_name }}' not found in namespace '{{ hertzbeat_namespace }}'"
      when: hertzbeat_current_deployment.resources is not defined or hertzbeat_current_deployment.resources | length == 0

    - name: Validate HerzBeat manifest with kubectl (dry-run)
      shell: kubectl apply -f "{{ hertzbeat_manifest_path }}" --context="{{ k8s_context }}" --dry-run=server --validate=true
      register: kubectl_validate_result
      failed_when: kubectl_validate_result.rc != 0

    - name: Apply HerzBeat manifest from local file (server-side)
      kubernetes.core.k8s:
        state: present
        src: "{{ hertzbeat_manifest_path }}"
        context: "{{ k8s_context }}"
        server_side_apply:
          field_manager: "ansible-hertzbeat-upgrade"
      register: hertzbeat_apply_result
      failed_when: hertzbeat_apply_result.failed | default(false)

    - name: Display HerzBeat manifest validation and application result
      debug:
        msg:
          - "HerzBeat manifest validation and application:"
          - "  Kubectl validation: {{ 'SUCCESS' if kubectl_validate_result.rc == 0 else 'FAILED' }}"
          - "  Kubectl error: {{ kubectl_validate_result.stderr | default('None') }}"
          - "  Ansible result: {{ 'SUCCESS' if not (hertzbeat_apply_result.failed | default(false)) else 'FAILED' }}"
          - "  Changed: {{ hertzbeat_apply_result.changed }}"
          - "  Error: {{ hertzbeat_apply_result.msg | default('None') }}"

    - name: Wait for manifest application to complete
      pause:
        seconds: 5

    - name: Check if deployment was restarted by manifest application
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: "{{ hertzbeat_deployment_name }}"
        namespace: "{{ hertzbeat_namespace }}"
        context: "{{ k8s_context }}"
      register: hertzbeat_post_apply_deployment

    - name: Get current pod to check if restart is needed
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ hertzbeat_namespace }}"
        label_selectors:
          - "app=hertzbeat"
        context: "{{ k8s_context }}"
      register: hertzbeat_current_pods

    - name: Force pod restart if manifest didn't trigger restart
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Pod
        name: "{{ item.metadata.name }}"
        namespace: "{{ hertzbeat_namespace }}"
        context: "{{ k8s_context }}"
      loop: "{{ hertzbeat_current_pods.resources }}"
      when: 
        - hertzbeat_current_pods.resources is defined
        - hertzbeat_current_pods.resources | length > 0
        - not hertzbeat_apply_result.changed
      register: pod_deletion_result

    - name: Display pod restart action
      debug:
        msg: 
          - "Pod restart status:"
          - "  Manifest caused restart: {{ hertzbeat_apply_result.changed }}"
          - "  Manual pod deletion performed: {{ pod_deletion_result.changed | default(false) }}"

    - name: Wait for HerzBeat deployment to be ready
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: "{{ hertzbeat_deployment_name }}"
        namespace: "{{ hertzbeat_namespace }}"
        context: "{{ k8s_context }}"
        wait: true
        wait_condition:
          type: Available
          status: "True"
        wait_timeout: 300
      register: hertzbeat_deployment_ready

    - name: Get updated HerzBeat deployment (after upgrade)
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: "{{ hertzbeat_deployment_name }}"
        namespace: "{{ hertzbeat_namespace }}"
        context: "{{ k8s_context }}"
      register: hertzbeat_updated_deployment

    - name: Display updated HerzBeat status
      debug:
        msg:
          - "Updated HerzBeat Deployment:"
          - "  Name: {{ hertzbeat_updated_deployment.resources[0].metadata.name }}"
          - "  Image: {{ hertzbeat_updated_deployment.resources[0].spec.template.spec.containers[0].image }}"
          - "  Ready Replicas: {{ hertzbeat_updated_deployment.resources[0].status.readyReplicas }}/{{ hertzbeat_updated_deployment.resources[0].status.replicas }}"
          - "  Status: {{ hertzbeat_updated_deployment.resources[0].status.conditions[-1].type }}"

    - name: Extract version information from container images
      set_fact:
        hertzbeat_previous_image: "{{ hertzbeat_current_deployment.resources[0].spec.template.spec.containers[0].image | default('Unknown') }}"
        hertzbeat_current_image: "{{ hertzbeat_updated_deployment.resources[0].spec.template.spec.containers[0].image }}"

    - name: Display upgrade summary
      debug:
        msg:
          - "HerzBeat upgrade completed successfully!"
          - "Previous image: {{ hertzbeat_previous_image }}"
          - "Current image: {{ hertzbeat_current_image }}"
          - "Manifest applied: {{ hertzbeat_apply_result.changed }}"
          - "Pod restart triggered: {{ hertzbeat_apply_result.changed or (pod_deletion_result.changed | default(false)) }}"
          - "Deployment ready: {{ hertzbeat_deployment_ready.resources[0].status.conditions[-1].status == 'True' }}"