---
- name: Upgrade VictoriaMetrics using Helm
  hosts: localhost
  gather_facts: false
  vars:
    helm_release_name: "vmoperator"
    helm_chart_name: "vm/victoria-metrics-operator"
    helm_namespace: "victoriametrics"
    helm_values_file: "{{ playbook_dir }}/../../k3s-config/victoriametrics/helm/victoriametrics-values-prod-operator.yaml"
    k8s_context: "k3s-prod"
  tasks:
    - name: Update Helm repositories
      kubernetes.core.helm_repository:
        name: vm
        repo_url: https://victoriametrics.github.io/helm-charts/
        state: present

    - name: Get current VictoriaMetrics version (before upgrade)
      kubernetes.core.helm_info:
        name: "{{ helm_release_name }}"
        namespace: "{{ helm_namespace }}"
        release_state: deployed
        kube_context: "{{ k8s_context }}"
      register: victoriametrics_current_version
      ignore_errors: true

    - name: Display current VictoriaMetrics version
      debug:
        msg:
          - "Current VictoriaMetrics release:"
          - "  Name: {{ victoriametrics_current_version.status.name | default('Not installed') }}"
          - "  Version: {{ victoriametrics_current_version.status.chart | default('Unknown') }}"
          - "  App Version: {{ victoriametrics_current_version.status.app_version | default('Unknown') }}"
          - "  Status: {{ victoriametrics_current_version.status.status | default('Unknown') }}"
      when: victoriametrics_current_version.status is defined

    - name: Display installation status if not found
      debug:
        msg: "VictoriaMetrics release '{{ helm_release_name }}' not found in namespace '{{ helm_namespace }}'"
      when: victoriametrics_current_version.status is not defined

    - name: Upgrade VictoriaMetrics using Helm
      kubernetes.core.helm:
        name: "{{ helm_release_name }}"
        chart_ref: "{{ helm_chart_name }}"
        namespace: "{{ helm_namespace }}"
        values_files:
          - "{{ helm_values_file }}"
        state: present
        update_repo_cache: true
        kube_context: "{{ k8s_context }}"
        wait: true
        wait_timeout: "300s"
      register: victoriametrics_upgrade_result

    - name: Get updated VictoriaMetrics version (after upgrade)
      kubernetes.core.helm_info:
        name: "{{ helm_release_name }}"
        namespace: "{{ helm_namespace }}"
        release_state: deployed
        kube_context: "{{ k8s_context }}"
      register: victoriametrics_updated_version

    - name: Display updated VictoriaMetrics version
      debug:
        msg:
          - "Updated VictoriaMetrics release:"
          - "  Name: {{ victoriametrics_updated_version.status.name }}"
          - "  Version: {{ victoriametrics_updated_version.status.chart }}"
          - "  App Version: {{ victoriametrics_updated_version.status.app_version }}"
          - "  Status: {{ victoriametrics_updated_version.status.status }}"
          - "  Revision: {{ victoriametrics_updated_version.status.revision }}"

    - name: Display upgrade summary
      debug:
        msg:
          - "VictoriaMetrics upgrade completed successfully!"
          - "{% if victoriametrics_current_version.status is defined %}Previous version: {{ victoriametrics_current_version.status.chart | default('Unknown') }}{% endif %}"
          - "Current version: {{ victoriametrics_updated_version.status.chart }}"
          - "Upgrade performed: {{ victoriametrics_upgrade_result.changed }}"