---
- name: Upgrade Cert-Manager using Helm
  hosts: localhost
  gather_facts: false
  vars:
    helm_release_name: "cert-manager"
    helm_chart_name: "jetstack/cert-manager"
    helm_namespace: "cert-manager"
    helm_values_file: "{{ playbook_dir }}/../../k3s-config/cert-manager/helm/cert-manager-values-prod.yaml"
    k8s_context: "k3s-prod"
  tasks:
    - name: Update Helm repositories
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io
        state: present

    - name: Get current Cert-Manager version (before upgrade)
      kubernetes.core.helm_info:
        name: "{{ helm_release_name }}"
        namespace: "{{ helm_namespace }}"
        release_state: deployed
        kube_context: "{{ k8s_context }}"
      register: certmanager_current_version
      ignore_errors: true

    - name: Display current Cert-Manager version
      debug:
        msg:
          - "Current Cert-Manager release:"
          - "  Name: {{ certmanager_current_version.status.name | default('Not installed') }}"
          - "  Version: {{ certmanager_current_version.status.chart | default('Unknown') }}"
          - "  App Version: {{ certmanager_current_version.status.app_version | default('Unknown') }}"
          - "  Status: {{ certmanager_current_version.status.status | default('Unknown') }}"
      when: certmanager_current_version.status is defined

    - name: Display installation status if not found
      debug:
        msg: "Cert-Manager release '{{ helm_release_name }}' not found in namespace '{{ helm_namespace }}'"
      when: certmanager_current_version.status is not defined

    - name: Upgrade Cert-Manager using Helm
      kubernetes.core.helm:
        name: "{{ helm_release_name }}"
        chart_ref: "{{ helm_chart_name }}"
        namespace: "{{ helm_namespace }}"
        values_files:
          - "{{ helm_values_file }}"
        state: present
        update_repo_cache: true
        kube_context: "{{ k8s_context }}"
        wait: true
        wait_timeout: "300s"
      register: certmanager_upgrade_result

    - name: Get updated Cert-Manager version (after upgrade)
      kubernetes.core.helm_info:
        name: "{{ helm_release_name }}"
        namespace: "{{ helm_namespace }}"
        release_state: deployed
        kube_context: "{{ k8s_context }}"
      register: certmanager_updated_version

    - name: Display updated Cert-Manager version
      debug:
        msg:
          - "Updated Cert-Manager release:"
          - "  Name: {{ certmanager_updated_version.status.name }}"
          - "  Version: {{ certmanager_updated_version.status.chart }}"
          - "  App Version: {{ certmanager_updated_version.status.app_version }}"
          - "  Status: {{ certmanager_updated_version.status.status }}"
          - "  Revision: {{ certmanager_updated_version.status.revision }}"

    - name: Display upgrade summary
      debug:
        msg:
          - "Cert-Manager upgrade completed successfully!"
          - "{% if certmanager_current_version.status is defined %}Previous version: {{ certmanager_current_version.status.chart | default('Unknown') }}{% endif %}"
          - "Current version: {{ certmanager_updated_version.status.chart }}"
          - "Upgrade performed: {{ certmanager_upgrade_result.changed }}"