---
- name: Upgrade Zigbee2MQTT using local manifest across multiple instances
  hosts: localhost
  gather_facts: false
  vars:
    service_name: "zigbee2mqtt"
    instances:
      - name: "11"
        context: "k3s-prod"
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/zigbee2mqtt/manifests/zigbee2mqtt-prod-11.yaml"
        deployment_name: "zigbee11"
        service_namespace: "zigbee2mqtt"
        app_label: "zigbee11"
      - name: "15"
        context: "k3s-prod"
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/zigbee2mqtt/manifests/zigbee2mqtt-prod-15.yaml"
        deployment_name: "zigbee15"
        service_namespace: "zigbee2mqtt"
        app_label: "zigbee15"
  tasks:
    - name: Run multi-instance manifest upgrade tasks
      include_tasks: ../../tasks/common-update-manifest-multi.yaml
