---
- name: Upgrade Home Assistant using local manifest across multiple contexts
  hosts: localhost
  gather_facts: false
  vars:
    service_name: "homeassistant"
    instances:
      - name: "morgspi"
        context: "k3s-morgspi"
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/homeassistant/manifests/homeassistant-morgspi.yaml"
        deployment_name: "homeassistant"
        service_namespace: "homeassistant"
        app_label: "homeassistant"
      - name: "mudderpi"
        context: "k3s-mudderpi"
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/homeassistant/manifests/homeassistant-mudderpi.yaml"
        deployment_name: "homeassistant"
        service_namespace: "homeassistant"
        app_label: "homeassistant"
      - name: "prod"
        context: "k3s-prod"
        manifest_path: "{{ playbook_dir }}/../../files/k3s-config/homeassistant/manifests/homeassistant-prod.yaml"
        deployment_name: "homeassistant"
        service_namespace: "homeassistant"
        app_label: "homeassistant"
  tasks:
    - name: Run multi-instance manifest upgrade tasks
      include_tasks: ../../tasks/common-update-manifest-multi.yaml
