---
- name: Upgrade MetalLB using Helm
  hosts: localhost
  gather_facts: false
  vars:
    service_name: "metallb"
    helm_release_name: "metallb"
    helm_chart_name: "metallb/metallb"
    helm_repo_name: "metallb"
    helm_repo_url: "https://metallb.github.io/metallb"
    helm_namespace: "metallb-system"
    helm_values_file: "{{ playbook_dir }}/../../k3s-config/metallb/helm/metallb-values-prod.yaml"
    k8s_context: "k3s-prod"
  tasks:
    - name: Run helm upgrade tasks
      include_tasks: ../../tasks/common-update-helm.yaml
