---
- name: Upgrade Traefik using Helm
  hosts: localhost
  gather_facts: false
  vars:
    service_name: "traefik"
    helm_release_name: "traefik"
    helm_chart_name: "traefik/traefik"
    helm_repo_name: "traefik"
    helm_repo_url: "https://traefik.github.io/charts"
    helm_namespace: "traefik"
    helm_values_file: "{{ playbook_dir }}/../../k3s-config/traefik/helm/traefik-values-prod.yaml"
    k8s_context: "k3s-prod"
  tasks:
    - name: Run helm upgrade tasks
      include_tasks: ../../tasks/common-update-helm.yaml
