---
- name: Upgrade OpenSearch using Helm
  hosts: localhost
  gather_facts: false
  vars:
    service_name: "opensearch"
    helm_release_name: "opensearch"
    helm_chart_name: "opensearch/opensearch"
    helm_repo_name: "opensearch"
    helm_repo_url: "https://opensearch-project.github.io/helm-charts/"
    helm_namespace: "opensearch"
    helm_values_file: "{{ playbook_dir }}/../../files/k3s-config/opensearch/helm/opensearch-values-prod.yaml"
    k8s_context: "k3s-prod"
  tasks:
    - name: Run helm upgrade tasks
      include_tasks: ../../tasks/common-update-helm.yaml
