---
- name: Ensure user 'dang' exists
  ansible.builtin.user:
    name: dang
    state: present
  when: inventory_hostname in groups['lxc']

- name: Set password for user 'dang'
  ansible.builtin.user:
    name: dang
    password: "{{ vault_dang_password | password_hash('sha512') }}"
    update_password: on_create
  when: inventory_hostname in groups['lxc']

- name: Add dang to sudoers
  ansible.builtin.user:
    name: dang
    groups: sudo
    append: true
  when: inventory_hostname in groups['lxc']

- name: Allow sudo group to sudo without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/sudo-group-nopasswd
    line: '%sudo ALL=(ALL) NOPASSWD:ALL'
    create: true
    mode: '0440'
  when: inventory_hostname in groups['lxc']

- name: Set SSH public key variable
  ansible.builtin.set_fact:
    lxc_ssh_public_key: "{{ awx_ssh_public_key | default(ssh_public_key | default('')) }}"
  when: inventory_hostname in groups['lxc']

- name: Validate SSH public key is provided
  ansible.builtin.fail:
    msg: "SSH public key is required but not provided. Ensure ssh_public_key is defined in vault or AWX credentials."
  when:
    - inventory_hostname in groups['lxc']
    - lxc_ssh_public_key == ''

- name: Add SSH public key for dang
  ansible.builtin.lineinfile:
    path: /home/dang/.ssh/authorized_keys
    line: "{{ lxc_ssh_public_key }}"
    create: true
    owner: dang
    group: dang
    mode: '0600'
  when: inventory_hostname in groups['lxc']
