---
- name: Copy smb cifs credentials
  ansible.builtin.copy:
    src: smb/smb_cifs_credentials.secret
    dest: /etc/smb_cifs_credentials
    decrypt: true
    owner: root
    group: root
    mode: '0600'
  when: ansible_hostname != 'adambalm'

- name: Create smb media directory
  ansible.builtin.file:
    path: /mnt/smb_media
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Mount smb media directory
  ansible.posix.mount:
    src: //smb.goepp.net/media
    path: /mnt/smb_media
    state: mounted
    fstype: cifs
    opts: credentials=/etc/smb_cifs_credentials

- name: Create smb kopia-hdd directory
  ansible.builtin.file:
    path: /mnt/kopia-hdd
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: inventory_hostname in groups['k3s_prod']

- name: Mount smb kopia-hdd directory
  ansible.posix.mount:
    src: //smb.goepp.net/kopia-hdd
    path: /mnt/kopia-hdd
    state: mounted
    fstype: cifs
    opts: credentials=/etc/smb_cifs_credentials
  when: inventory_hostname in groups['k3s_prod']
