---
- name: Set CIFS credentials variables
  ansible.builtin.set_fact:
    cifs_user: "{{ awx_cifs_username | default(cifs_username | default('')) }}"
    cifs_pass: "{{ awx_cifs_password | default(cifs_password | default('')) }}"
  when: ansible_hostname != 'adambalm'

- name: Validate CIFS credentials are provided
  ansible.builtin.fail:
    msg: "CIFS credentials are required but not provided. Ensure cifs_username and cifs_password are defined in vault or AWX credentials."
  when:
    - ansible_hostname != 'adambalm'
    - cifs_user == '' or cifs_pass == ''

- name: Create CIFS credentials file
  ansible.builtin.copy:
    content: |
      username={{ cifs_user }}
      password={{ cifs_pass }}
    dest: /etc/smb_cifs_credentials
    owner: root
    group: root
    mode: '0600'
  when: ansible_hostname != 'adambalm'

- name: Create smb media directory
  ansible.builtin.file:
    path: /mnt/smb_media
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Mount smb media directory
  ansible.posix.mount:
    src: //smb.goepp.net/media
    path: /mnt/smb_media
    state: mounted
    fstype: cifs
    opts: credentials=/etc/smb_cifs_credentials

- name: Create smb kopia-hdd directory
  ansible.builtin.file:
    path: /mnt/kopia-hdd
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: inventory_hostname in groups['k3s_prod']

- name: Mount smb kopia-hdd directory
  ansible.posix.mount:
    src: //smb.goepp.net/kopia-hdd
    path: /mnt/kopia-hdd
    state: mounted
    fstype: cifs
    opts: credentials=/etc/smb_cifs_credentials
  when: inventory_hostname in groups['k3s_prod']
