# Ansible Inventory - converted from ~/.ansible/hosts
all:

  hosts:

    localhost:
      ansible_connection: local

  children:

    pve:
      hosts:
        pve11:
        pve12:
        pve13:
        pve15:
      vars:
        ansible_user: root

    ubuntu:
      hosts:
        ui-network:
        backup:
        dev:
        adambalm:

    rpi:
      hosts:
        rockyledge:
          services: ['nut']
        morgspi:
          services: ['nut', 'homeassistant']
        mudderpi:
          services: ['nut', 'homeassistant']
        probepi:
        magpi:
        voicepi-greatroom:
          services: ['wyoming']
          wyoming_satellite_name: "Greatroom Satellite"

    k3s_prod:
      hosts:
        k3s-prod-11:
        k3s-prod-12:
        k3s-prod-13:
        k3s-prod-15:

    lxc:
      hosts:
        smb:

    ui_protect:
      hosts:
        ui-protect:
          ansible_user: root