---
- name: Ensure user 'dang' exists
  ansible.builtin.user:
    name: dang
    state: present

- name: Set password for user 'dang'
  ansible.builtin.user:
    name: dang
    password: "{{ vault_dang_password | password_hash('sha512') }}"
    update_password: on_create

- name: Add dang to sudoers
  ansible.builtin.user:
    name: dang
    groups: sudo
    append: true

- name: Allow sudo group to sudo without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/sudo-group-nopasswd
    line: '%sudo ALL=(ALL) NOPASSWD:ALL'
    create: true
    mode: '0440'

- name: Add SSH public key for dang
  ansible.builtin.lineinfile:
    path: /home/dang/.ssh/authorized_keys
    line: "{{ lookup('file', inventory_dir + '/../files/ssh/dang_id_rsa.pub.secret') }}"
    create: true
    owner: dang
    group: dang
    mode: '0600'
