---
- name: Upgrade pgAdmin using Helm
  hosts: localhost
  gather_facts: false
  vars:
    helm_release_name: "pgadmin"
    helm_chart_name: "runix/pgadmin4"
    helm_namespace: "pgadmin"
    helm_values_file: "/Users/dang/Documents/Development/k3s-config/pgadmin/helm/pgadmin-values-prod.yaml"
    k8s_context: "k3s-prod"
  tasks:
    - name: Update Helm repositories
      kubernetes.core.helm_repository:
        name: runix
        repo_url: https://helm.runix.net
        state: present

    - name: Get current pgAdmin version (before upgrade)
      kubernetes.core.helm_info:
        name: "{{ helm_release_name }}"
        namespace: "{{ helm_namespace }}"
        release_state: deployed
        kube_context: "{{ k8s_context }}"
      register: pgadmin_current_version
      ignore_errors: true

    - name: Display current pgAdmin version
      debug:
        msg:
          - "Current pgAdmin release:"
          - "  Name: {{ pgadmin_current_version.status.name | default('Not installed') }}"
          - "  Version: {{ pgadmin_current_version.status.chart | default('Unknown') }}"
          - "  App Version: {{ pgadmin_current_version.status.app_version | default('Unknown') }}"
          - "  Status: {{ pgadmin_current_version.status.status | default('Unknown') }}"
      when: pgadmin_current_version.status is defined

    - name: Display installation status if not found
      debug:
        msg: "pgAdmin release '{{ helm_release_name }}' not found in namespace '{{ helm_namespace }}'"
      when: pgadmin_current_version.status is not defined

    - name: Upgrade pgAdmin using Helm
      kubernetes.core.helm:
        name: "{{ helm_release_name }}"
        chart_ref: "{{ helm_chart_name }}"
        namespace: "{{ helm_namespace }}"
        values_files:
          - "{{ helm_values_file }}"
        state: present
        update_repo_cache: true
        kube_context: "{{ k8s_context }}"
        wait: true
        wait_timeout: "300s"
      register: pgadmin_upgrade_result

    - name: Get updated pgAdmin version (after upgrade)
      kubernetes.core.helm_info:
        name: "{{ helm_release_name }}"
        namespace: "{{ helm_namespace }}"
        release_state: deployed
        kube_context: "{{ k8s_context }}"
      register: pgadmin_updated_version

    - name: Display updated pgAdmin version
      debug:
        msg:
          - "Updated pgAdmin release:"
          - "  Name: {{ pgadmin_updated_version.status.name }}"
          - "  Version: {{ pgadmin_updated_version.status.chart }}"
          - "  App Version: {{ pgadmin_updated_version.status.app_version }}"
          - "  Status: {{ pgadmin_updated_version.status.status }}"
          - "  Revision: {{ pgadmin_updated_version.status.revision }}"

    - name: Display upgrade summary
      debug:
        msg:
          - "pgAdmin upgrade completed successfully!"
          - "{% if pgadmin_current_version.status is defined %}Previous version: {{ pgadmin_current_version.status.chart | default('Unknown') }}{% endif %}"
          - "Current version: {{ pgadmin_updated_version.status.chart }}"
          - "Upgrade performed: {{ pgadmin_upgrade_result.changed }}"