---
- name: Upgrade MongoDB using Helm
  hosts: localhost
  gather_facts: false
  vars:
    helm_release_name: "community-operator"
    helm_chart_name: "mongodb/community-operator"
    helm_namespace: "mongodb"
    # helm_values_file: "/Users/dang/Documents/Development/k3s-config/mongodb/helm/mongodb-values-prod.yaml"
    k8s_context: "k3s-prod"
  tasks:
    - name: Update Helm repositories
      kubernetes.core.helm_repository:
        name: mongodb
        repo_url: https://mongodb.github.io/helm-charts
        state: present

    - name: Get current MongoDB version (before upgrade)
      kubernetes.core.helm_info:
        name: "{{ helm_release_name }}"
        namespace: "{{ helm_namespace }}"
        release_state: deployed
        kube_context: "{{ k8s_context }}"
      register: mongodb_current_version
      ignore_errors: true

    - name: Display current MongoDB version
      debug:
        msg:
          - "Current MongoDB release:"
          - "  Name: {{ mongodb_current_version.status.name | default('Not installed') }}"
          - "  Version: {{ mongodb_current_version.status.chart | default('Unknown') }}"
          - "  App Version: {{ mongodb_current_version.status.app_version | default('Unknown') }}"
          - "  Status: {{ mongodb_current_version.status.status | default('Unknown') }}"
      when: mongodb_current_version.status is defined

    - name: Display installation status if not found
      debug:
        msg: "MongoDB release '{{ helm_release_name }}' not found in namespace '{{ helm_namespace }}'"
      when: mongodb_current_version.status is not defined

    - name: Upgrade MongoDB using Helm
      kubernetes.core.helm:
        name: "{{ helm_release_name }}"
        chart_ref: "{{ helm_chart_name }}"
        namespace: "{{ helm_namespace }}"
        # values_files:
        #   - "{{ helm_values_file }}"
        state: present
        update_repo_cache: true
        kube_context: "{{ k8s_context }}"
        wait: true
        wait_timeout: "300s"
      register: mongodb_upgrade_result

    - name: Get updated MongoDB version (after upgrade)
      kubernetes.core.helm_info:
        name: "{{ helm_release_name }}"
        namespace: "{{ helm_namespace }}"
        release_state: deployed
        kube_context: "{{ k8s_context }}"
      register: mongodb_updated_version

    - name: Display updated MongoDB version
      debug:
        msg:
          - "Updated MongoDB release:"
          - "  Name: {{ mongodb_updated_version.status.name }}"
          - "  Version: {{ mongodb_updated_version.status.chart }}"
          - "  App Version: {{ mongodb_updated_version.status.app_version }}"
          - "  Status: {{ mongodb_updated_version.status.status }}"
          - "  Revision: {{ mongodb_updated_version.status.revision }}"

    - name: Display upgrade summary
      debug:
        msg:
          - "MongoDB upgrade completed successfully!"
          - "{% if mongodb_current_version.status is defined %}Previous version: {{ mongodb_current_version.status.chart | default('Unknown') }}{% endif %}"
          - "Current version: {{ mongodb_updated_version.status.chart }}"
          - "Upgrade performed: {{ mongodb_upgrade_result.changed }}"