---
- name: Test Ceph NoOut Flag Management
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Display test information
      debug:
        msg: |
          Testing Ceph noout flag management
          Target Ceph host: {{ groups['pve'][0] }}

    - name: Enable Ceph noout flag (TEST)
      include_tasks: ../tasks/ops-upgrade-cluster-ceph-noout.yaml
      vars:
        maintenance_action: enable

    - name: Pause to review noout status
      pause:
        prompt: |

          Ceph noout flag has been ENABLED.

          You can verify this by running on a Ceph node:
          ssh {{ groups['pve'][0] }} "ceph osd dump | grep flags"

          Press Enter to continue and DISABLE the noout flag...

    - name: Disable Ceph noout flag (TEST)
      include_tasks: ../tasks/ops-upgrade-cluster-ceph-noout.yaml
      vars:
        maintenance_action: disable

    - name: Test completed
      debug:
        msg: |
          Ceph noout flag test completed.

          The noout flag should now be disabled.
          Verify with: ssh {{ groups['pve'][0] }} "ceph osd dump | grep flags"