- name: Upgrade Portainer on adambalm
  hosts: adambalm
  become: true
  gather_facts: false

  tasks:

    - name: Stop existing Portainer container
      docker_container:
        name: portainer
        state: stopped
      ignore_errors: true

    - name: Remove existing Portainer container
      docker_container:
        name: portainer
        state: absent
      ignore_errors: true

    - name: Pull latest Portainer CE image
      docker_image:
        name: portainer/portainer-ce:latest
        source: pull
        force_source: true
        force_tag: true

    - name: Start new Portainer container
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: always
        ports:
          - "8000:8000"
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

    - name: Wait for Portainer to be ready
      uri:
        url: https://localhost:9443
        method: GET
        validate_certs: false
        status_code: [200, 302]
      retries: 30
      delay: 2
      delegate_to: "{{ inventory_hostname }}"