---
- name: Test Cluster Alerts Management
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/common.yml

  tasks:
    - name: Display test information
      debug:
        msg: |
          Testing cluster alerts mute/unmute functionality
          This will test: Graylog, Alertmanager, and HerzBeat

    - name: Enable alerts maintenance mode (TEST)
      include_tasks: ../tasks/ops-upgrade-cluster-alerts.yaml
      vars:
        maintenance_action: enable

    - name: Pause to review muted status
      pause:
        prompt: |

          Alerts have been MUTED across all monitoring systems.

          You can verify this by checking:
          - Graylog: Check for maintenance notifications
          - Alertmanager: Check for silences
          - HerzBeat: Check for monitoring silences

          Press Enter to continue and UNMUTE alerts...

    - name: Disable alerts maintenance mode (TEST)
      include_tasks: ../tasks/ops-upgrade-cluster-alerts.yaml
      vars:
        maintenance_action: disable

    - name: Test completed
      debug:
        msg: |
          Alerts mute/unmute test completed.

          All monitoring systems should now be restored to normal operation.
          Verify alerts are working in your monitoring dashboards.