# - name: System Version Check Report
#   hosts: "ubuntu:k3s_prod:rpi"
#   gather_facts: true
#   become: false
#   tasks:
  
#   - name: Print host data
#     debug:
#       msg: "{{ '%-18s' | format(inventory_hostname[:18]) }} │ {{ '%-16s' | format((ansible_distribution + ' ' + ansible_distribution_version)[:16]) }} │ {{ '%-20s' | format(ansible_kernel[:20]) }} │ {{ ansible_lsb.description | default('N/A') }}"
#     delegate_to: localhost

- name: Version Checker Operations
  hosts: localhost
  gather_facts: true
  vars:
    version_checker_path: "{{ ansible_env.HOME }}/Documents/Development/version-checker"
  tasks:

  - name: List all applications in version tracker
    shell: |
      cd {{ version_checker_path }}
      source venv/bin/activate
      ./check_versions.py --list
    register: version_list
    when: version_check_action is defined and version_check_action == "list"

  - name: Check all application versions
    shell: |
      cd {{ version_checker_path }}
      source venv/bin/activate
      ./check_versions.py --check-all
    register: version_check_all
    when: version_check_action is defined and version_check_action == "check-all"

  - name: Show version summary
    shell: |
      cd {{ version_checker_path }}
      source venv/bin/activate
      ./check_versions.py --summary
    register: version_summary
    when: version_check_action is defined and version_check_action == "summary"

  - name: Check specific application
    shell: |
      cd {{ version_checker_path }}
      source venv/bin/activate
      ./check_versions.py --app "{{ app_name }}"
    register: version_app_check
    when: version_check_action is defined and version_check_action == "app" and app_name is defined

  - name: Display version list results
    debug:
      msg: "{{ version_list.stdout_lines }}"
    when: version_list is defined and version_list.stdout_lines is defined

  - name: Display check-all results
    debug:
      msg: "{{ version_check_all.stdout_lines }}"
    when: version_check_all is defined and version_check_all.stdout_lines is defined

  - name: Display summary results
    debug:
      msg: "{{ version_summary.stdout_lines }}"
    when: version_summary is defined and version_summary.stdout_lines is defined

  - name: Display app check results
    debug:
      msg: "{{ version_app_check.stdout_lines }}"
    when: version_app_check is defined and version_app_check.stdout_lines is defined

