- name: unifi network server install
  hosts: "ui-network"
  become: true

  tasks:
  
    # Install cert renewal script
    
    - name: Download cert renewal script
      ansible.builtin.get_url:
        url: https://get.glennr.nl/unifi/extra/unifi-easy-encrypt.sh
        dest: /usr/local/bin/unifi-easy-encrypt.sh
        mode: '0755'

    - name: copy cloudflare.ini
      copy:
        src: ../files/cloudflare/cloudflare.ini.secret
        decrypt: yes
        dest: /root/cloudflare.ini
        owner: root
        group: root
        mode: 0600

    - name: cron cert renewal
      cron:
        name: cert renewal
        weekday: "6"
        hour: "2"
        minute: "0"
        job: 'unifi-easy-encrypt.sh --skip --email dan@goepp.com --fqdn ui-network.goepp.net --dns-challenge --dns-provider cloudflare --dns-provider-credentials /root/cloudflare.ini --server-ip 10.1.254.10 --external-dns 10.1.254.1'

    - name: Add backup server SSH public key for root
      authorized_key:
        user: root
        key: "{{ lookup('file', '../files/ssh/dang_id_rsa.pub.secret') }}"
        comment: "backup server access"
