- name: backup server setup
  hosts: "backup"
  become: true

  handlers:

  tasks:

    # Create backup directories
    - name: create backup directories
      file:
        path: "/mnt/backups/{{ item }}"
        state: directory
        owner: root
        group: sudo
        mode: 0775
      loop:
        - opnsense
        - homeassistant
        - zigbee2mqtt
        - esphome
        - kopia
        - uptime-kuma
        - torrent
        - jira
        - victoriametrics
        - unifi

    # Setup SSH key for backup access to other servers
    - name: Create .ssh directory for root
      file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: 0700

    - name: Install SSH private key for root
      copy:
        src: ../files/ssh/dang_id_rsa.secret
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: 0600

    # Install backup script - main
    - name: copy backup script
      copy:
        src: ../files/backup/backups.sh
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: 0755

    # Install backup script - jira
    - name: copy backup script
      copy:
        src: ../files/backup/jira_backup.py
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: 0755

    # Install backup config - opnsense
    - name: copy backup config - opnsense
      copy:
        src: ../files/backup/.opnsense.env.secret
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: 0755

    # Install backup config - jira
    - name: copy jira backup config
      copy:
        src: ../files/backup/jira.ini.secret
        dest: /usr/local/etc/jira.ini
        owner: root
        group: root
        mode: 0660

    # Install victoria metrics utilities
    - name: download victoria metrics utilities
      ansible.builtin.get_url:
        url: https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.109.1/vmutils-linux-amd64-v1.109.1.tar.gz
        dest: /usr/local/src/vmutils-linux-amd64-v1.109.1.tar.gz
        mode: '0644'
    - name: extract victoria metrics utilities
      ansible.builtin.unarchive:
        src: /usr/local/src/vmutils-linux-amd64-v1.109.1.tar.gz
        dest: /usr/local/bin/
        creates: /usr/local/bin/vmbackup-prod
        remote_src: yes

    # Cron main backups script
    - name: cron main backup
      cron:
        name: main backup
        hour: "23"
        minute: "0"
        job: '/usr/local/bin/backups.sh'

    # Cron jira backup script
    - name: cron jira backup
      cron:
        name: jira backup
        hour: "0"
        minute: "0"
        weekday: "6"
        job: '/usr/bin/python3 /usr/local/bin/jira_backup.py'