---
- name: Apply common base configuration
  hosts: "all:!pve"
  become: true
  roles:
    - common

- name: Install extra virtual packages for ubuntu VMs
  hosts: "k3s_prod:ubuntu:!smb"
  become: true
  tasks:
    - name: Install extra virtual packages for ubuntu VMs
      ansible.builtin.apt:
        name:
          - linux-image-extra-virtual
        state: present
        update_cache: true
      when: ansible_virtualization_type != "NA"

    - name: Stop and disable multipathd service
      ansible.builtin.systemd:
        name: multipathd.service
        state: stopped
        enabled: false

    - name: Stop and disable multipathd socket
      ansible.builtin.systemd:
        name: multipathd.socket
        state: stopped
        enabled: false

- name: Configure user dang
  hosts: "all:!pve"
  become: false
  remote_user: dang
  tasks:
    - name: Create ansible tmp directory for dang
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.ansible/tmp"
        state: directory
        mode: '0755'

    - name: Configure oh-my-zsh for dang
      ansible.builtin.import_tasks: ../roles/common/tasks/oh-my-zsh.yaml

    - name: Setup user settings (git and vim)
      ansible.builtin.import_tasks: ../roles/common/tasks/user.yaml
